using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TinderBot2._0
{
    public class TinderLists
    {
        public static object[] Ethnicities =
        {
            "Caucasian",
            "Asian",
            "African American",
            "Latin(x)",
            "Indian",
        };

        public static Dictionary<string, long> JobData = new(StringComparer.OrdinalIgnoreCase)
        {
            { "Janitor", 26000 },
            { "Customer Service", 30000 },
            { "CSR", 30000 },
            { "Nurse", 64000 },
            { "Teacher", 50000 },
            { "Account Manager", 42000 },
            { "Vet Tech", 30000 },
            { "Game Ops", 50000 },
            { "Electronics Assembler", 32000 },
            { "Instructional Assistant", 30000 },
            { "Barista", 24000 },
            { "Pharmacy Technician", 40000 },
            { "Software Developer", 75000 },
            { "Interior Designer", 50000 },
            { "Mortgage Officer", 35000 },
            { "Educator", 40000 },
            { "Accountant", 52000 },
            { "Accounting", 52000 },
            { "Receptionist", 28000 },
            { "Police", 48000 },
            { "Bartender", 22000 },
            { "Retail", 29000 },
            { "Auditor", 75000 },
            { "Personal Care Aid", 21000 },
            { "Sales Representative", 66000 },
            { "Nursing Assistant", 27000 },
            { "Truck Driver", 43000 },
            { "General Manager", 60000 },
            { "GM", 60000 },
            { "Preschool Teacher", 35000 },
            { "Secretary", 35000 },
            { "Administrative Assistant", 35000 },
            { "Freight", 28000 },
            { "Waiter", 23000 },
            { "Waitress", 23000 },
            { "Office Clerk", 31000 },
            { "Mathmatician", 60000 },
            { "Cashier", 21000 },
            { "Urologist", 396000 },
            { "Radiologist", 375000 },
            { "Brain Surgeon", 393000 },
            { "Hedge Fund Manager", 312000 },
            { "Dermatologist", 306000 },
            { "Anesthesiologist", 300000 },
            { "Cardiologist", 300000 },
            { "Pediatrician", 157000 },
            { "Dentist", 149000 },
            { "Air Traffic Controller", 122000 },
            { "Marketing Manager", 119000 },
            { "Pharmacist", 116000 },
            { "Lawyer", 113000 },
            { "HR Director", 99000 },
            { "Translator", 45000 },
            { "Etsy", 20000 },
            { "Optician", 44000 },
            { "Real Estate Broker", 42000 },
            { "Carpenter", 40000 },
            { "Correctional Officer", 40000 },
            { "Welder", 37000 },
            { "DJ", 40000 },
            { "Deejay", 40000 },
            { "Roofer", 38000 },
            { "Journalist", 36000 },
            { "Massage Therapist", 36000 },
            { "Dental Assistant", 34500 },
            { "Fisherman", 34000 },
            { "Wedding Planner", 32000 },
            { "Personal Trainer", 32000 },
            { "EMT", 31000 },
            { "Housekeeper", 20000 },
            { "Lifeguard", 20000 },
            { "Uber", 25000 },
            { "Lyft", 25000 },
            { "DoorDash", 25000 },
            { "Bus Driver", 34000 },
            { "Mechanic", 38000 },
            { "Flight Attendant", 38000 },
            { "Locksmith", 40000 },
            { "Machinist", 40000 },
            { "CNC", 40000 },
            { "Social Worker", 44000 },
            { "Fire Fighter", 45000 },
            { "Chef", 47000 },
            { "Plumber", 50000 },
            { "Ecologist", 50000 },
            { "Parole Officer", 52000 },
            { "Librarian", 55000 },
            { "Historian", 55000 },
            { "Zoologist", 60000 },
            { "Chiropractor", 60000 },
            { "Web Designer", 65000 },
            { "Coroner", 70000 },
            { "Psychologist", 72000 },
            { "Film Director", 75000 },
            { "Film Producer", 75000 },
            { "Chemist", 72000 },
            { "Law Firm", 65000 },
            { "Pet Tech", 43000 },
            { "Area Manager", 44000 },
            { "Sales", 55000 },
            { "Scientist", 60000 },
            { "Packaging", 32000 },
            { "Warehouse", 31000 },
            { "Registered Medical Assistant", 36000 },
            { "Video Journalist", 68000 },
            { "Hospitality Management", 48000 },
            { "Legal Analyst", 62241 },
            { "Tax Attorney", 101000 },
            { "Tutor", 30000 },
            { "Daycare Teacher", 19000 },
            { "Cosmetology Instructor", 45000 },
            { "Dishwasher", 20000 },
            { "Deli Clerk", 22000 },
            { "Bar Manager", 30000 },
            { "Custodian", 21000 },
            { "Exterminator", 37000 },
            { "Night Cleaner", 20000 },
            { "Senior Data Analyst", 75000 },
            { "Teller", 26000 },
            { "Stocker", 22000 },
            { "Bank Teller", 26000 },
            { "Data Entry", 25000 },
            { "Electrician", 35000 },
        };

        public static object[] StarSigns =
        {
            "Aries",
            "Taurus",
            "Gemini",
            "Cancer",
            "Leo",
            "Virgo",
            "Libra",
            "Scorpio",
            "Sagittarius",
            "Aquarius",
            "Pisces",
            "Capricorn"
        };

        public static object[] Hobbies =
        {
            "Harry Potter",
            "90s Kid",
            "SoundCloud",
            "Spa",
            "Self Care",
            "Heavy Metal",
            "House Parties",
            "Gin Tonic",
            "Gymnastics",
            "Hot Yoga",
            "Meditation",
            "Spotify",
            "Sushi",
            "Hockey",
            "Basketball",
            "Slam Poetry",
            "Home Workout",
            "Theater",
            "Cafe Hopping",
            "Aquarium",
            "Sneakers",
            "Instagram",
            "Hot Springs",
            "Walking",
            "Running",
            "Travel",
            "Language Exchange",
            "Movies",
            "Guitarists",
            "Social Development",
            "Gym",
            "Social Media",
            "Hip Hop",
            "Skincare",
            "J-Pop",
            "Shisha",
            "Cricket",
            "Freelance",
            "Skateboarding",
            "Gospel",
            "K-Pop",
            "Potterhead",
            "Trying New Things",
            "Photography",
            "Bollywood",
            "Reading",
            "Singing",
            "Sports",
            "Poetry",
            "Stand up Comedy",
            "Coffee",
            "Karaoke",
            "Fortnite",
            "Free Diving",
            "Self Development",
            "Mental Health Awareness",
            "Foodie Tour",
            "Voter Rights",
            "Jui-jitsu",
            "Climate Change",
            "Exhibition",
            "Walking My Dog",
            "LGBTQ+ Rights",
            "Feminism",
            "VR Room",
            "Escape Cafe",
            "Shopping",
            "Brunch",
            "Investment",
            "Second-hand apparel",
            "Jetski",
            "Reggaeton",
            "Black Lives Matter",
            "Jogging",
            "Road Trips",
            "Vintage Fashion",
            "Voguing",
            "Couchsurfing",
            "Happy Hour",
            "Incluvisity",
            "Country Music",
            "Football",
            "Inline Skate",
            "Investing",
            "Tennis",
            "Ice Cream",
            "Ice Skating",
            "Human Rights",
            "Expositions",
            "Skiing",
            "Pig Roast",
            "Snowboarding",
            "Canoeing",
            "West End Musicals",
            "Pilates",
            "Pentathlon",
            "Broadway",
            "PlayStation",
            "Cheerleading",
            "Choir",
            "Pole Dancing",
            "Five-a-side Football",
            "Car Racing",
            "Pinterest",
            "Festivals",
            "Pub Quiz",
            "Catan",
            "Cosplay",
            "Motor Sports",
            "Coffee Stall",
            "Content Creation",
            "E-Sports",
        };
    }
}